### ISSUE TITLE
Issue with portal gun in multiplayer

### ISSUE THREAD

**Issue by ghost** [iChun/PortalGunClassic#4]
[crash-2019-01-27_20.00.38-client.txt](https://github.com/iChun/PortalGunClassic/files/2801051/crash-2019-01-27_20.00.38-client.txt)

**Comment by iChun** [comment]
`java.lang.NullPointerException: portalgun:block_portal from mod PortalGun returned a null ItemStack in getPickBlock(...). Please report this to them.
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:143)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_470_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:480)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:202)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.renderWorldPortal(WorldPortalRenderer.java:127)
`

**Comment by iChun** [comment]
Should be fixed in PG 7.1.0.
